services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: unless-stopped

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: mi_proyecto_wp_wordpress
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_NAME: 'wordpress'
      WORDPRESS_DB_USER: 'wordpress_user'
      WORDPRESS_DB_PASSWORD: 'password_wordpress'
    restart: always
