; Pool de configuración para WordPress
[www]

; Usuario y grupo bajo el que se ejecutará el proceso
user = www-data
group = www-data

; LA LÍNEA MÁGICA: Escuchar en el puerto 9000 en lugar de un socket de Unix (.sock)
listen = 9000

; Permisos de escucha
listen.owner = www-data
listen.group = www-data

; Configuración básica de gestión de procesos (workers)
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3