[mysqld]

# 1. Permisos y puertos
user = mysql
port = 3306

# 2. El enchufe interno
socket = /run/mysqld/mysqld.sock

# 3. La ruta de los datos (El volumen persistente)
datadir = /var/lib/mysql

# 4. LA LÍNEA MÁGICA: Escuchar al exterior
bind-address = 0.0.0.0